.\" command for multiple tasks
.TH man 8 "25 Oct 2020" "v0.1.0" "internsct1 man page"
.SH NAME
internsct1 
.SH SYNOPSIS
internsct1 [OPTIONS]
.SH DESCRIPTION
internsct1 is a custom linux command via bash script which perform several commands for file information or system information
.SH OPTIONS
Try out following options:
	cpu getinfo					get information about CPU of server
	memory getinfo				get information about memory of server
	user create <username>		create a new user on the server
	user list					list all the users on the server
	user list --sudo-only		list all the users with sudo permissions on the server
  	--help 						print this help message and exit
 	--version 					print version of this command
	file getinfo <file-name>	get information about a file on the server
.SH BUGS
No known bugs.
.SH AUTHOR
Vishal Kumar
